### PR TITLE
add clamp

### PR DESCRIPTION
**Pull request by giogonzo**

### CODE REVIEW

**Comment by giogonzo** [comment]
@gcanti I think this is ready to go, care to take a look?

**Comment by gcanti** [comment]
```ts
return (low: A, hi?: A, x?: A) => {
  if (hi === undefined) {
  }
}
```

@giogonzo there's a possible corner case when `A = undefined`

**Comment by giogonzo** [comment]
This test is somehow passing already:
```ts
const ordUndefined: Ord<undefined> = {
      equals: (a, b) => a === b,
      compare: () => 0
    };
    expect(
      JSONEqual(R.clamp(undefined, undefined, undefined), FR.clamp(ordUndefined)(undefined, undefined, undefined))
    ).toBe(true);
```

**Comment by giogonzo** [comment]
yes, it fails without the `JSON.stringify`:
```
expected: undefined
received: [Function]
```

**Comment by giogonzo** [comment]
@gcanti added support for it in the last commit, but it has a perf cost. Probably it can be improved by switching back to `function` instead of `() =>` and accessing `arguments.length`

**Comment by giogonzo** [comment]
Tracking further perf improvements in #13

**Pull request merged**
